
/**************************************************************
 *	
 *	gameMusic, 8 bit, 11025Hz,
 *	1 channel, 1940256 bytes/channel
 *	Total Size: 1 * 1940256 + 4 (header) = 1940300 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\gameMusic.wav
 *	Time-stamp: Sun Nov 26 23:24:51 2017
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 1940256

extern const unsigned char gameMusic[1940256];

#endif /* __GAMEMUSICH__ */
