
/**************************************************************
 *	
 *	gameMusic, 8 bit, 11025Hz,
 *	1 channel, 139524 bytes/channel
 *	Total Size: 1 * 139524 + 4 (header) = 139568 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\gameMusic.wav
 *	Time-stamp: Wed Nov 29 19:00:59 2017
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 139524

extern const unsigned char gameMusic[139524];

#endif /* __GAMEMUSICH__ */
