
/**************************************************************
 *	
 *	gudetama, 8 bit, 11025Hz,
 *	1 channel, 16106 bytes/channel
 *	Total Size: 1 * 16106 + 4 (header) = 16150 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\gudetama.wav
 *	Time-stamp: Thu Nov 30 18:05:39 2017
 *	
 **************************************************************/

#ifndef __GUDETAMAH__
#define __GUDETAMAH__

#define GUDETAMAFREQ 11025
#define GUDETAMALEN 16106

extern const unsigned char gudetama[16106];

#endif /* __GUDETAMAH__ */
