
/**************************************************************
 *	
 *	hit, 8 bit, 11025Hz,
 *	1 channel, 2068 bytes/channel
 *	Total Size: 1 * 2068 + 4 (header) = 2112 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\hit.wav
 *	Time-stamp: Sun Nov 26 22:49:39 2017
 *	
 **************************************************************/

#ifndef __HITH__
#define __HITH__

#define HITFREQ 11025
#define HITLEN 2068

extern const unsigned char hit[2068];

#endif /* __HITH__ */
