
/**************************************************************
 *	
 *	loseMusic, 8 bit, 11025Hz,
 *	1 channel, 67610 bytes/channel
 *	Total Size: 1 * 67610 + 4 (header) = 67654 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\loseMusic.wav
 *	Time-stamp: Wed Nov 29 18:53:40 2017
 *	
 **************************************************************/

#ifndef __LOSEMUSICH__
#define __LOSEMUSICH__

#define LOSEMUSICFREQ 11025
#define LOSEMUSICLEN 67610

extern const unsigned char loseMusic[67610];

#endif /* __LOSEMUSICH__ */
