
/**************************************************************
 *	
 *	loseMusic, 8 bit, 11025Hz,
 *	1 channel, 277935 bytes/channel
 *	Total Size: 1 * 277935 + 4 (header) = 277979 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\loseMusic.wav
 *	Time-stamp: Sun Nov 26 22:43:55 2017
 *	
 **************************************************************/

#ifndef __LOSEMUSICH__
#define __LOSEMUSICH__

#define LOSEMUSICFREQ 11025
#define LOSEMUSICLEN 277935

extern const unsigned char loseMusic[277935];

#endif /* __LOSEMUSICH__ */
