
/**************************************************************
 *	
 *	pauseMusic, 8 bit, 11025Hz,
 *	1 channel, 200201 bytes/channel
 *	Total Size: 1 * 200201 + 4 (header) = 200245 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\pauseMusic.wav
 *	Time-stamp: Sun Dec 03 17:01:31 2017
 *	
 **************************************************************/

#ifndef __PAUSEMUSICH__
#define __PAUSEMUSICH__

#define PAUSEMUSICFREQ 11025
#define PAUSEMUSICLEN 200201

extern const unsigned char pauseMusic[200201];

#endif /* __PAUSEMUSICH__ */
