
/**************************************************************
 *	
 *	pauseMusic, 8 bit, 11025Hz,
 *	1 channel, 185569 bytes/channel
 *	Total Size: 1 * 185569 + 4 (header) = 185613 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\pauseMusic.wav
 *	Time-stamp: Tue Dec 05 19:08:47 2017
 *	
 **************************************************************/

#ifndef __PAUSEMUSICH__
#define __PAUSEMUSICH__

#define PAUSEMUSICFREQ 11025
#define PAUSEMUSICLEN 185569

extern const unsigned char pauseMusic[185569];

#endif /* __PAUSEMUSICH__ */
