
/**************************************************************
 *	
 *	shoot, 8 bit, 11025Hz,
 *	1 channel, 2299 bytes/channel
 *	Total Size: 1 * 2299 + 4 (header) = 2343 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\shoot.wav
 *	Time-stamp: Sun Nov 26 21:32:23 2017
 *	
 **************************************************************/

#ifndef __SHOOTH__
#define __SHOOTH__

#define SHOOTFREQ 11025
#define SHOOTLEN 2299

extern const unsigned char shoot[2299];

#endif /* __SHOOTH__ */
