
/**************************************************************
 *	
 *	splashMusic, 8 bit, 11025Hz,
 *	1 channel, 2017440 bytes/channel
 *	Total Size: 1 * 2017440 + 4 (header) = 2017484 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\splashMusic.wav
 *	Time-stamp: Sun Nov 26 23:24:26 2017
 *	
 **************************************************************/

#ifndef __SPLASHMUSICH__
#define __SPLASHMUSICH__

#define SPLASHMUSICFREQ 11025
#define SPLASHMUSICLEN 2017440

extern const unsigned char splashMusic[2017440];

#endif /* __SPLASHMUSICH__ */
