
/**************************************************************
 *	
 *	splashMusic, 8 bit, 11025Hz,
 *	1 channel, 199757 bytes/channel
 *	Total Size: 1 * 199757 + 4 (header) = 199801 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\splashMusic.wav
 *	Time-stamp: Wed Nov 29 18:47:44 2017
 *	
 **************************************************************/

#ifndef __SPLASHMUSICH__
#define __SPLASHMUSICH__

#define SPLASHMUSICFREQ 11025
#define SPLASHMUSICLEN 199757

extern const unsigned char splashMusic[199757];

#endif /* __SPLASHMUSICH__ */
