
/**************************************************************
 *	
 *	winMusic, 8 bit, 11025Hz,
 *	1 channel, 119001 bytes/channel
 *	Total Size: 1 * 119001 + 4 (header) = 119045 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\david\Dropbox\School\CS2261.2\FinalProject\winMusic.wav
 *	Time-stamp: Wed Nov 29 21:05:49 2017
 *	
 **************************************************************/

#ifndef __WINMUSICH__
#define __WINMUSICH__

#define WINMUSICFREQ 11025
#define WINMUSICLEN 119001

extern const unsigned char winMusic[119001];

#endif /* __WINMUSICH__ */
